networks:
  default:
    name: hadoop-docker-bridge
    external: true

services:
  hive:
    image: 15521147129/bigdata:hive-3.1.2
    hostname: hive
    container_name: hive
    user: hive
    command: /bin/bash -c "/dockerentry/run.sh"
    restart: no
    # restart: always
    ports:
      - 9083:9083
      - 10000:10000
      - 10002:10002
    environment:
      - PREREQUISITE_SERVERS=mysql-3306:hadoop101-8088
      - TZ=Asia/Shanghai
    tty: true
