networks:
  default:
    name: hadoop-docker-bridge
    external: true

services:
  hadoop101:
    platform: linux/amd64
    image: 15521147129/bigdata:hadoop-3.1.4
    hostname: hadoop101
    container_name: hadoop101
    user: hadoop
    command: sh -c "/dockerentry/run-namenode.sh"
    restart: no
    # restart: always
    ports:
      - 9000:9000
      - 10020:10020
      - 19888:19888
      - 8032:8032
      - 8030:8030
      - 8031:8031
      - 8088:8088
      - 9870:9870
      - 9864:9864
      - 9866:9866
      - 9867:9867
      - 19:22
    tty: true

  hadoop102:
    platform: linux/amd64
    image: 15521147129/bigdata:hadoop-3.1.4
    hostname: hadoop102
    container_name: hadoop102
    user: hadoop
    command: sh -c "/dockerentry/run-datanode.sh"
    restart: no
    # restart: always
    ports:
      - 8888:8888
      - 19866:9866
      - 20:22
#    environment:
#      - PREREQUISITE_SERVERS=hadoop101-9870:hadoop103-9868
    tty: true

  hadoop103:
    platform: linux/amd64
    image: 15521147129/bigdata:hadoop-3.1.4
    hostname: hadoop103
    container_name: hadoop103
    user: hadoop
    command: sh -c "/dockerentry/run-datanode.sh"
    restart: no
    # restart: always
    ports:
      - 9868:9868
      - 29866:9866
      - 21:22
    tty: true
