networks:
  default:
    name: hadoop-docker-bridge
    external: true

services:
  hadoop101:
    platform: linux/amd64
    image: 15521147129/bigdata:mysql-5.6.37
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #指定用户密码
      TZ: Asia/Shanghai
    user: mysql
    command: sh -c "/dockerentry/setup-mysql-for-hive.sh"
    restart: always
    ports:
      - 3307:3306
    tty: true
